version: '3'

services: 
  webserver:
    container_name: webserver
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./latihan:/usr/share/nginx/html/latihan