version: '3'

services:
  webserver:
    container_name: webserver
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - /root/pemweb/pemrograman_web/pert2/coding/src:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
